apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: package-tracking
  projectName: abc-transport
  annotations:
    componentType: buildpackService
spec:
  inbound:
    - name: package-tracking
      port: 3000
      type: REST
      context: .
      schemaFilePath: openapi.yaml
